import type { Metadata } from "next";
import { Fustat } from "next/font/google"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fustat = Fustat({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800']
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fustat.className} geometric-fustat bg-grey-100 3xl:mx-60 4xl:mx-96`}
      >
        {children}
      </body>
    </html>
  );
}